apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guest
  namespace: development
spec:
  type: business-unit
  profile:
    displayName: default
  parent: ops
  children: []
  members: []
