apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guest
spec:
  type: business-unit
  profile:
    displayName: guest
  parent: ops
  children: [backstage, other]
  members: ["default/guest"]
